### ISSUE TITLE
Integrate Travis CI service

### ISSUE THREAD

**Issue by peter279k** [HylianShield/number-generator#1]
As title, can I integrate the Travis CI service?
And I also can enhance the tests.
If possible, I can help this issue and send the PR.

Thanks.

**Comment by janmartenjongerius** [comment]
What is it you are looking for by integrating Travis CI? Is it a coverage badge? A build badge? CI feedback during pull requests? I would actually prefer setting up Scrutinizer combined with having `mediact/testing-suite` as dev-requirement for this package, to integrate a more feature complete dev street. See https://github.com/mediact/testing-suite

**Comment by peter279k** [comment]
It's the CI service and it can also add the ```code-coverage``` during the Travis CI build.

Please see other repo [Travis CI build log](https://travis-ci.org/Th3Mouk/YahooWeatherAPI/jobs/384893954).

Thanks.

**Comment by janmartenjongerius** [comment]
Thanks @peter279k. I'm quite familiar with Travis as a CI. My question was really about what you are looking to improve on the current package. Are you missing badges in the README? Do you want better feedback for when you open a pull request with enhanced tests?
I'm also quite curious about in what manner you would want to enhance the unit test for the number generator. Did you encounter a scenario where the number generator was behaving in an unexpected fashion, perhaps?

**Comment by peter279k** [comment]
@johmanx10 . Yes, I will create the PR to discuss this.

Thanks.

**Comment by janmartenjongerius** [comment]
This issue has been resolved by the corresponding pull request

**Comment by janmartenjongerius** [comment]
@peter279k what is your interest in this package, if I may be so bold?

**Comment by peter279k** [comment]
I am interested in this package about the random number.
And I want to have this package better.
I also concern other interesting packages in this organization.
If possible, I can help others, too.
